import { useState, useEffect, useRef } from "react"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { Progress } from "@/components/ui/progress"
import { Badge } from "@/components/ui/badge"
import { Separator } from "@/components/ui/separator"
import { Toaster } from "@/components/ui/toaster"
import { Toaster as Sonner } from "@/components/ui/sonner"
import { TooltipProvider } from "@/components/ui/tooltip"
import { QueryClient, QueryClientProvider } from "@tanstack/react-query"
import { BrowserRouter, Routes, Route } from "react-router-dom"
import {
  startAnalysis,
  getWorkflowStatus,
  getWorkflowResult,
  StockResult,
  WorkflowStatus,
  ActivityLogEntry,
  MCPStatus,
} from "@/lib/api"
import { AnalysisResponse } from "@/lib/types"
import {
  TrendingUp,
  TrendingDown,
  Target,
  AlertTriangle,
  CheckCircle,
  XCircle,
  AlertCircle,
  BarChart3,
  FileText,
  RefreshCw,
  Zap,
  Play,
  Sun,
  Moon,
  Copy,
  Download,
  Printer,
  Check,
} from "lucide-react"

// Import new components
import { ProcessFlow } from "@/components/ProcessFlow"
import { ActivityLog } from "@/components/ActivityLog"
import { StockSearch } from "@/components/StockSearch"

const queryClient = new QueryClient()

const App = () => (
  <QueryClientProvider client={queryClient}>
    <TooltipProvider>
      <Toaster />
      <Sonner />
      <BrowserRouter>
        <Routes>
          <Route path="/" element={<Index />} />
          <Route path="*" element={<NotFound />} />
        </Routes>
      </BrowserRouter>
    </TooltipProvider>
  </QueryClientProvider>
)

export default App

const defaultMCPStatus: MCPStatus = {
  financials: 'idle',
  valuation: 'idle',
  volatility: 'idle',
  macro: 'idle',
  news: 'idle',
  sentiment: 'idle',
}

const Index = () => {
  const [selectedStock, setSelectedStock] = useState<StockResult | null>(null)
  const [isLoading, setIsLoading] = useState(false)
  const [showResults, setShowResults] = useState(false)
  const [activeTab, setActiveTab] = useState("analysis")
  const [isDark, setIsDark] = useState(true)
  const [analysisResult, setAnalysisResult] = useState<AnalysisResponse | null>(null)
  const [workflowId, setWorkflowId] = useState<string | null>(null)

  // Workflow tracking
  const [currentStep, setCurrentStep] = useState<string>('idle')
  const [completedSteps, setCompletedSteps] = useState<string[]>([])
  const [mcpStatus, setMcpStatus] = useState<MCPStatus>(defaultMCPStatus)
  const [activityLog, setActivityLog] = useState<ActivityLogEntry[]>([])
  const [revisionCount, setRevisionCount] = useState(0)
  const [score, setScore] = useState(0)
  const [llmProvider, setLlmProvider] = useState<string>('')
  const [cacheHit, setCacheHit] = useState(false)

  const [copied, setCopied] = useState(false)
  const pollingRef = useRef<NodeJS.Timeout | null>(null)

  useEffect(() => {
    document.documentElement.classList.toggle("dark", isDark)
  }, [isDark])

  // Export functions
  const formatSwotForClipboard = () => {
    if (!analysisResult) return ''
    return `SWOT Analysis: ${analysisResult.company_name}
Quality Score: ${analysisResult.score}/10
Revisions: ${analysisResult.revision_count}

STRENGTHS:
${analysisResult.swot_data.strengths.map(s => `- ${s}`).join('\n')}

WEAKNESSES:
${analysisResult.swot_data.weaknesses.map(w => `- ${w}`).join('\n')}

OPPORTUNITIES:
${analysisResult.swot_data.opportunities.map(o => `- ${o}`).join('\n')}

THREATS:
${analysisResult.swot_data.threats.map(t => `- ${t}`).join('\n')}

QUALITY EVALUATION:
${analysisResult.critique}

---
Generated by A2A Strategy Agent`
  }

  const copyToClipboard = async () => {
    try {
      await navigator.clipboard.writeText(formatSwotForClipboard())
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    } catch (err) {
      console.error('Failed to copy:', err)
    }
  }

  const downloadAsJson = () => {
    if (!analysisResult) return
    const exportData = {
      ...analysisResult,
      exported_at: new Date().toISOString()
    }
    const blob = new Blob([JSON.stringify(exportData, null, 2)], { type: 'application/json' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `swot-analysis-${analysisResult.company_name.toLowerCase().replace(/\s+/g, '-')}.json`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  const handleGenerate = async () => {
    if (!selectedStock) return

    setIsLoading(true)
    setShowResults(false)
    setCurrentStep('input')
    setCompletedSteps([])
    setMcpStatus(defaultMCPStatus)
    setActivityLog([])
    setRevisionCount(0)
    setScore(0)
    setCacheHit(false)

    try {
      const { workflow_id } = await startAnalysis(
        selectedStock.name,
        selectedStock.symbol,
        'Competitive Position'
      )
      setWorkflowId(workflow_id)
      setCompletedSteps(['input'])
      setCurrentStep('cache')

      // Start polling
      pollingRef.current = setInterval(async () => {
        try {
          const status = await getWorkflowStatus(workflow_id)

          // Update state from status
          setRevisionCount(status.revision_count)
          setScore(status.score)
          setActivityLog(status.activity_log || [])
          setMcpStatus(status.mcp_status || defaultMCPStatus)
          if (status.provider_used) setLlmProvider(status.provider_used)

          // Track completed steps
          const stepOrder = ['input', 'cache', 'researcher', 'analyzer', 'critic', 'editor', 'output']
          const currentIdx = stepOrder.indexOf(status.current_step)
          if (currentIdx > 0) {
            setCompletedSteps(stepOrder.slice(0, currentIdx))
          }
          setCurrentStep(status.current_step)

          // Check for cache hit
          if (status.data_source === 'cached') {
            setCacheHit(true)
          }

          if (status.status === "completed") {
            clearInterval(pollingRef.current!)
            pollingRef.current = null

            const result = await getWorkflowResult(workflow_id)
            setAnalysisResult(result)
            setCompletedSteps(stepOrder)
            setCurrentStep('completed')
            setIsLoading(false)
            setShowResults(true)
          } else if (status.status === "error") {
            clearInterval(pollingRef.current!)
            pollingRef.current = null
            setIsLoading(false)
          }
        } catch (error) {
          console.error("Polling error:", error)
        }
      }, 700)

    } catch (error) {
      console.error("Error starting analysis:", error)
      setIsLoading(false)
    }
  }

  useEffect(() => {
    return () => {
      if (pollingRef.current) {
        clearInterval(pollingRef.current)
      }
    }
  }, [])

  const getScoreColor = (score: number) => {
    if (score >= 7) return "text-emerald-400"
    if (score >= 5) return "text-yellow-400"
    return "text-red-400"
  }

  const getScoreBadge = (score: number) => {
    if (score >= 7)
      return { label: "Board-ready", variant: "default" as const, icon: CheckCircle }
    if (score >= 5)
      return { label: "Acceptable", variant: "secondary" as const, icon: AlertCircle }
    return { label: "Needs Review", variant: "destructive" as const, icon: XCircle }
  }

  const handleStockClear = () => {
    setSelectedStock(null)
    setShowResults(false)
    setAnalysisResult(null)
    setCurrentStep('idle')
    setCompletedSteps([])
    setActivityLog([])
  }

  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <header className="border-b border-border bg-card sticky top-0 z-40">
        <div className="container mx-auto px-4 sm:px-6 py-3">
          <div className="flex items-center justify-between gap-4">
            <div className="shrink-0">
              <h1 className="text-lg font-semibold text-foreground">
                AI Strategy Copilot
              </h1>
              <p className="text-xs text-muted-foreground hidden sm:block">
                with self-evaluating agents
              </p>
            </div>
            <div className="flex-1 max-w-xl">
              <StockSearch
                onSelect={setSelectedStock}
                selectedStock={selectedStock}
                onClear={handleStockClear}
                disabled={isLoading}
              />
            </div>
            <Button
              variant="ghost"
              size="icon"
              onClick={() => setIsDark(!isDark)}
              className="h-9 w-9 shrink-0"
            >
              {isDark ? <Sun className="h-4 w-4" /> : <Moon className="h-4 w-4" />}
            </Button>
          </div>
        </div>
      </header>

      <main className="container mx-auto px-4 sm:px-6 py-6 space-y-6">

        {/* Generate Button */}
        {selectedStock && !showResults && !isLoading && (
          <div className="flex justify-center">
            <Button
              onClick={handleGenerate}
              size="lg"
              className="gap-2 btn-glow"
            >
              <Play className="h-5 w-5" />
              Generate SWOT
            </Button>
          </div>
        )}

        {/* Process Flow - visible during and after execution */}
        {(isLoading || showResults) && (
          <ProcessFlow
            currentStep={currentStep}
            completedSteps={completedSteps}
            mcpStatus={mcpStatus}
            llmProvider={llmProvider}
            cacheHit={cacheHit}
          />
        )}

        {/* Activity Log - visible during execution */}
        {isLoading && (
          <ActivityLog entries={activityLog} />
        )}

        {/* Empty State */}
        {!selectedStock && !isLoading && !showResults && (
          <Card className="flex flex-col items-center justify-center py-16">
            <BarChart3 className="h-12 w-12 text-muted-foreground/30 mb-4" />
            <h2 className="text-xl font-medium text-foreground mb-2">
              Enter a company name to begin
            </h2>
            <p className="text-muted-foreground text-center max-w-md">
              Strategic analysis powered by multi-agent AI
            </p>
          </Card>
        )}

        {/* Results */}
        {showResults && analysisResult && (
          <div className="space-y-6 animate-slide-up">
            {/* Results Header */}
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
              <div>
                <h2 className="text-2xl font-semibold text-foreground">
                  {analysisResult.company_name} ({selectedStock?.symbol})
                </h2>
                <p className="text-sm text-muted-foreground">
                  {selectedStock?.exchange}
                </p>
              </div>
              <div className="flex flex-wrap items-center gap-4">
                {/* Metrics */}
                <div className="flex items-center gap-4">
                  <div className="text-center px-4 py-2 bg-card rounded-lg border">
                    <p className="text-xs text-muted-foreground">Confidence</p>
                    <p className={`text-xl font-bold ${getScoreColor(analysisResult.score)}`}>
                      {Math.round(analysisResult.score * 10)}%
                    </p>
                  </div>
                  <div className="text-center px-4 py-2 bg-card rounded-lg border">
                    <p className="text-xs text-muted-foreground">Score</p>
                    <p className={`text-xl font-bold ${getScoreColor(analysisResult.score)}`}>
                      {analysisResult.score}/10
                    </p>
                  </div>
                  <div className="text-center px-4 py-2 bg-card rounded-lg border">
                    <p className="text-xs text-muted-foreground">Revisions</p>
                    <p className="text-xl font-bold text-foreground">
                      {analysisResult.revision_count}
                    </p>
                  </div>
                  {llmProvider && (
                    <div className="text-center px-4 py-2 bg-card rounded-lg border">
                      <p className="text-xs text-muted-foreground">LLM</p>
                      <p className="text-sm font-medium text-foreground">
                        {llmProvider}
                      </p>
                    </div>
                  )}
                </div>
                <Badge variant={getScoreBadge(analysisResult.score).variant} className="gap-1.5">
                  {(() => {
                    const BadgeIcon = getScoreBadge(analysisResult.score).icon
                    return <BadgeIcon className="h-4 w-4" />
                  })()}
                  {getScoreBadge(analysisResult.score).label}
                </Badge>
              </div>
            </div>

            {/* Export Buttons */}
            <div className="flex flex-wrap gap-2 print:hidden">
              <Button variant="outline" size="sm" onClick={copyToClipboard} className="gap-1.5">
                {copied ? <Check className="h-4 w-4 text-emerald-500" /> : <Copy className="h-4 w-4" />}
                {copied ? "Copied!" : "Copy"}
              </Button>
              <Button variant="outline" size="sm" onClick={downloadAsJson} className="gap-1.5">
                <Download className="h-4 w-4" />
                Export JSON
              </Button>
              <Button variant="outline" size="sm" onClick={() => window.print()} className="gap-1.5">
                <Printer className="h-4 w-4" />
                Print
              </Button>
            </div>

            {/* Full View - Tabs with detailed info */}
            <Tabs value={activeTab} onValueChange={setActiveTab}>
                  <TabsList className="grid w-full grid-cols-4">
                    <TabsTrigger value="analysis" className="gap-1.5">
                      <BarChart3 className="h-4 w-4" />
                      SWOT
                    </TabsTrigger>
                    <TabsTrigger value="quality" className="gap-1.5">
                      <Target className="h-4 w-4" />
                      Quality
                    </TabsTrigger>
                    <TabsTrigger value="workflow" className="gap-1.5">
                      <RefreshCw className="h-4 w-4" />
                      Workflow
                    </TabsTrigger>
                    <TabsTrigger value="details" className="gap-1.5">
                      <FileText className="h-4 w-4" />
                      Details
                    </TabsTrigger>
                  </TabsList>

                  <TabsContent value="analysis" className="mt-6">
                    <div className="grid gap-4 md:grid-cols-2">
                      {/* Strengths Card */}
                      <Card className="border-l-4 border-l-emerald-500">
                        <CardHeader className="pb-3">
                          <CardTitle className="flex items-center gap-2 text-base text-emerald-500">
                            <TrendingUp className="h-5 w-5" />
                            Strengths
                          </CardTitle>
                        </CardHeader>
                        <CardContent>
                          <ul className="space-y-2">
                            {analysisResult.swot_data.strengths.map((item, i) => (
                              <li key={i} className="flex gap-2 text-sm text-foreground">
                                <CheckCircle className="h-4 w-4 text-emerald-500 shrink-0 mt-0.5" />
                                <span>{item}</span>
                              </li>
                            ))}
                          </ul>
                        </CardContent>
                      </Card>

                      {/* Weaknesses Card */}
                      <Card className="border-l-4 border-l-red-500">
                        <CardHeader className="pb-3">
                          <CardTitle className="flex items-center gap-2 text-base text-red-500">
                            <TrendingDown className="h-5 w-5" />
                            Weaknesses
                          </CardTitle>
                        </CardHeader>
                        <CardContent>
                          <ul className="space-y-2">
                            {analysisResult.swot_data.weaknesses.map((item, i) => (
                              <li key={i} className="flex gap-2 text-sm text-foreground">
                                <XCircle className="h-4 w-4 text-red-500 shrink-0 mt-0.5" />
                                <span>{item}</span>
                              </li>
                            ))}
                          </ul>
                        </CardContent>
                      </Card>

                      {/* Opportunities Card */}
                      <Card className="border-l-4 border-l-blue-500">
                        <CardHeader className="pb-3">
                          <CardTitle className="flex items-center gap-2 text-base text-blue-500">
                            <Target className="h-5 w-5" />
                            Opportunities
                          </CardTitle>
                        </CardHeader>
                        <CardContent>
                          <ul className="space-y-2">
                            {analysisResult.swot_data.opportunities.map((item, i) => (
                              <li key={i} className="flex gap-2 text-sm text-foreground">
                                <Zap className="h-4 w-4 text-blue-500 shrink-0 mt-0.5" />
                                <span>{item}</span>
                              </li>
                            ))}
                          </ul>
                        </CardContent>
                      </Card>

                      {/* Threats Card */}
                      <Card className="border-l-4 border-l-yellow-500">
                        <CardHeader className="pb-3">
                          <CardTitle className="flex items-center gap-2 text-base text-yellow-500">
                            <AlertTriangle className="h-5 w-5" />
                            Threats
                          </CardTitle>
                        </CardHeader>
                        <CardContent>
                          <ul className="space-y-2">
                            {analysisResult.swot_data.threats.map((item, i) => (
                              <li key={i} className="flex gap-2 text-sm text-foreground">
                                <AlertCircle className="h-4 w-4 text-yellow-500 shrink-0 mt-0.5" />
                                <span>{item}</span>
                              </li>
                            ))}
                          </ul>
                        </CardContent>
                      </Card>
                    </div>
                  </TabsContent>

                  <TabsContent value="quality" className="mt-6">
                    <div className="grid gap-6 md:grid-cols-2">
                      <Card>
                        <CardHeader>
                          <CardTitle className="text-base">Quality Metrics</CardTitle>
                        </CardHeader>
                        <CardContent className="space-y-6">
                          <div>
                            <div className="flex justify-between text-sm mb-2">
                              <span className="text-muted-foreground">Overall Score</span>
                              <span className={`font-medium ${getScoreColor(analysisResult.score)}`}>
                                {analysisResult.score}/10
                              </span>
                            </div>
                            <Progress value={analysisResult.score * 10} className="h-2" />
                          </div>
                          <Separator />
                          <div className="grid grid-cols-2 gap-4">
                            <div className="text-center p-4 rounded-lg bg-muted/50">
                              <p className="text-2xl font-bold text-foreground">
                                {analysisResult.revision_count}
                              </p>
                              <p className="text-sm text-muted-foreground">Revisions</p>
                            </div>
                            <div className="text-center p-4 rounded-lg bg-muted/50">
                              <p className="text-2xl font-bold text-foreground">
                                {analysisResult.report_length.toLocaleString()}
                              </p>
                              <p className="text-sm text-muted-foreground">Characters</p>
                            </div>
                          </div>
                        </CardContent>
                      </Card>

                      <Card>
                        <CardHeader>
                          <CardTitle className="text-base">Critic Evaluation</CardTitle>
                        </CardHeader>
                        <CardContent>
                          <p className="text-sm text-muted-foreground leading-relaxed">
                            {analysisResult.critique}
                          </p>
                        </CardContent>
                      </Card>
                    </div>
                  </TabsContent>

                  <TabsContent value="workflow" className="mt-6">
                    <ActivityLog entries={activityLog} />
                  </TabsContent>

                  <TabsContent value="details" className="mt-6">
                    <Card>
                      <CardHeader>
                        <CardTitle className="text-base">Process Information</CardTitle>
                      </CardHeader>
                      <CardContent className="space-y-4">
                        <div className="grid gap-4 md:grid-cols-2">
                          <div className="space-y-3">
                            <div className="flex justify-between py-2 border-b">
                              <span className="text-muted-foreground">Company</span>
                              <span className="font-medium">{analysisResult.company_name}</span>
                            </div>
                            <div className="flex justify-between py-2 border-b">
                              <span className="text-muted-foreground">Ticker</span>
                              <span className="font-medium">{selectedStock?.symbol}</span>
                            </div>
                            <div className="flex justify-between py-2 border-b">
                              <span className="text-muted-foreground">Exchange</span>
                              <span className="font-medium">{selectedStock?.exchange}</span>
                            </div>
                            <div className="flex justify-between py-2 border-b">
                              <span className="text-muted-foreground">Report Length</span>
                              <span className="font-medium">{analysisResult.report_length.toLocaleString()} chars</span>
                            </div>
                          </div>
                          <div className="p-4 rounded-lg bg-muted/50">
                            <h4 className="font-medium mb-3 flex items-center gap-2">
                              <RefreshCw className="h-4 w-4" />
                              Self-Correcting Process
                            </h4>
                            <ol className="text-sm text-muted-foreground space-y-2">
                              <li className="flex gap-2">
                                <span className="font-medium text-foreground">1.</span>
                                Researcher gathers data from 6 MCP servers
                              </li>
                              <li className="flex gap-2">
                                <span className="font-medium text-foreground">2.</span>
                                Analyst synthesizes SWOT with LLM
                              </li>
                              <li className="flex gap-2">
                                <span className="font-medium text-foreground">3.</span>
                                Critic evaluates quality (1-10 scale)
                              </li>
                              <li className="flex gap-2">
                                <span className="font-medium text-foreground">4.</span>
                                If score &lt; 7, Editor improves draft
                              </li>
                              <li className="flex gap-2">
                                <span className="font-medium text-foreground">5.</span>
                                Loop until quality ≥ 7 or max 3 revisions
                              </li>
                            </ol>
                          </div>
                        </div>
                      </CardContent>
                    </Card>
                  </TabsContent>
            </Tabs>
          </div>
        )}
      </main>

      {/* Footer */}
      <footer className="border-t border-border bg-card mt-auto">
        <div className="container mx-auto px-4 sm:px-6 py-3">
          <div className="flex items-center justify-center gap-4 text-xs text-muted-foreground">
            <span>AI Strategy Copilot</span>
            <span>|</span>
            <span>Multi-agent SWOT analysis</span>
            <span>|</span>
            <span>v2.0</span>
          </div>
        </div>
      </footer>
    </div>
  )
}

const NotFound = () => (
  <div className="min-h-screen bg-background flex flex-col items-center justify-center">
    <div className="text-center space-y-4">
      <h1 className="text-4xl font-bold text-foreground">404</h1>
      <p className="text-xl text-muted-foreground">Page Not Found</p>
      <Button onClick={() => window.location.href = '/'}>Go Home</Button>
    </div>
  </div>
)
