import { useState, useEffect, useRef } from "react"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { Badge } from "@/components/ui/badge"
import { Toaster } from "@/components/ui/toaster"
import { Toaster as Sonner } from "@/components/ui/sonner"
import { TooltipProvider } from "@/components/ui/tooltip"
import { QueryClient, QueryClientProvider } from "@tanstack/react-query"
import { BrowserRouter, Routes, Route } from "react-router-dom"
import {
  startAnalysis,
  getWorkflowStatus,
  getWorkflowResult,
  StockResult,
  WorkflowStatus,
  ActivityLogEntry,
  MCPStatus,
} from "@/lib/api"
import { AnalysisResponse } from "@/lib/types"
import {
  TrendingUp,
  TrendingDown,
  Target,
  AlertTriangle,
  CheckCircle,
  XCircle,
  AlertCircle,
  BarChart3,
  RefreshCw,
  Zap,
  Play,
  Sun,
  Moon,
  Copy,
  Download,
  Printer,
  Check,
} from "lucide-react"

// Import new components
import { ProcessFlow } from "@/components/ProcessFlow"
import { ActivityLog } from "@/components/ActivityLog"
import { StockSearch } from "@/components/StockSearch"

const queryClient = new QueryClient()

const App = () => (
  <QueryClientProvider client={queryClient}>
    <TooltipProvider>
      <Toaster />
      <Sonner />
      <BrowserRouter>
        <Routes>
          <Route path="/" element={<Index />} />
          <Route path="*" element={<NotFound />} />
        </Routes>
      </BrowserRouter>
    </TooltipProvider>
  </QueryClientProvider>
)

export default App

const defaultMCPStatus: MCPStatus = {
  financials: 'idle',
  valuation: 'idle',
  volatility: 'idle',
  macro: 'idle',
  news: 'idle',
  sentiment: 'idle',
}

const Index = () => {
  const [selectedStock, setSelectedStock] = useState<StockResult | null>(null)
  const [isLoading, setIsLoading] = useState(false)
  const [showResults, setShowResults] = useState(false)
  const [mainTab, setMainTab] = useState<"flow" | "results">("flow")
  const [isDark, setIsDark] = useState(true)
  const [analysisResult, setAnalysisResult] = useState<AnalysisResponse | null>(null)
  const [workflowId, setWorkflowId] = useState<string | null>(null)

  // Workflow tracking
  const [currentStep, setCurrentStep] = useState<string>('idle')
  const [completedSteps, setCompletedSteps] = useState<string[]>([])
  const [mcpStatus, setMcpStatus] = useState<MCPStatus>(defaultMCPStatus)
  const [activityLog, setActivityLog] = useState<ActivityLogEntry[]>([])
  const [revisionCount, setRevisionCount] = useState(0)
  const [score, setScore] = useState(0)
  const [llmProvider, setLlmProvider] = useState<string>('')
  const [cacheHit, setCacheHit] = useState(false)
  const [isSearching, setIsSearching] = useState(false)

  const [copied, setCopied] = useState(false)
  const pollingRef = useRef<NodeJS.Timeout | null>(null)

  useEffect(() => {
    document.documentElement.classList.toggle("dark", isDark)
  }, [isDark])

  // Export functions
  const formatSwotForClipboard = () => {
    if (!analysisResult) return ''
    return `SWOT Analysis: ${analysisResult.company_name}
Quality Score: ${analysisResult.score}/10
Revisions: ${analysisResult.revision_count}

STRENGTHS:
${analysisResult.swot_data.strengths.map(s => `- ${s}`).join('\n')}

WEAKNESSES:
${analysisResult.swot_data.weaknesses.map(w => `- ${w}`).join('\n')}

OPPORTUNITIES:
${analysisResult.swot_data.opportunities.map(o => `- ${o}`).join('\n')}

THREATS:
${analysisResult.swot_data.threats.map(t => `- ${t}`).join('\n')}

QUALITY EVALUATION:
${analysisResult.critique}

---
Generated by A2A Strategy Agent`
  }

  const copyToClipboard = async () => {
    try {
      await navigator.clipboard.writeText(formatSwotForClipboard())
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    } catch (err) {
      console.error('Failed to copy:', err)
    }
  }

  const downloadAsJson = () => {
    if (!analysisResult) return
    const exportData = {
      ...analysisResult,
      exported_at: new Date().toISOString()
    }
    const blob = new Blob([JSON.stringify(exportData, null, 2)], { type: 'application/json' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `swot-analysis-${analysisResult.company_name.toLowerCase().replace(/\s+/g, '-')}.json`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  const handleGenerate = async () => {
    if (!selectedStock) return

    setIsLoading(true)
    setShowResults(false)
    setCurrentStep('input')
    setCompletedSteps([])
    setMcpStatus(defaultMCPStatus)
    setActivityLog([])
    setRevisionCount(0)
    setScore(0)
    setCacheHit(false)

    try {
      const { workflow_id } = await startAnalysis(
        selectedStock.name,
        selectedStock.symbol,
        'Competitive Position'
      )
      setWorkflowId(workflow_id)
      setCompletedSteps(['input'])
      setCurrentStep('cache')

      // Start polling
      pollingRef.current = setInterval(async () => {
        try {
          const status = await getWorkflowStatus(workflow_id)

          // Update state from status
          setRevisionCount(status.revision_count)
          setScore(status.score)
          setActivityLog(status.activity_log || [])
          setMcpStatus(status.mcp_status || defaultMCPStatus)
          if (status.provider_used) setLlmProvider(status.provider_used)

          // Track completed steps
          const stepOrder = ['input', 'cache', 'researcher', 'analyzer', 'critic', 'editor', 'output']
          const currentIdx = stepOrder.indexOf(status.current_step)
          if (currentIdx > 0) {
            setCompletedSteps(stepOrder.slice(0, currentIdx))
          }
          setCurrentStep(status.current_step)

          // Check for cache hit
          if (status.data_source === 'cached') {
            setCacheHit(true)
          }

          if (status.status === "completed") {
            clearInterval(pollingRef.current!)
            pollingRef.current = null

            const result = await getWorkflowResult(workflow_id)
            setAnalysisResult(result)
            setCompletedSteps(stepOrder)
            setCurrentStep('completed')
            setIsLoading(false)
            setShowResults(true)
            setMainTab("results")  // Auto-switch to results tab
          } else if (status.status === "error") {
            clearInterval(pollingRef.current!)
            pollingRef.current = null
            setIsLoading(false)
          }
        } catch (error) {
          console.error("Polling error:", error)
        }
      }, 700)

    } catch (error) {
      console.error("Error starting analysis:", error)
      setIsLoading(false)
    }
  }

  useEffect(() => {
    return () => {
      if (pollingRef.current) {
        clearInterval(pollingRef.current)
      }
    }
  }, [])

  const getScoreColor = (score: number) => {
    if (score >= 7) return "text-emerald-400"
    if (score >= 5) return "text-yellow-400"
    return "text-red-400"
  }

  const getScoreBadge = (score: number) => {
    if (score >= 7)
      return { label: "Board-ready", variant: "default" as const, icon: CheckCircle }
    if (score >= 5)
      return { label: "Acceptable", variant: "secondary" as const, icon: AlertCircle }
    return { label: "Needs Review", variant: "destructive" as const, icon: XCircle }
  }

  const handleStockClear = () => {
    setSelectedStock(null)
    setShowResults(false)
    setAnalysisResult(null)
    setCurrentStep('idle')
    setCompletedSteps([])
    setActivityLog([])
  }

  return (
    <Tabs value={mainTab} onValueChange={(v) => setMainTab(v as "flow" | "results")} className="min-h-screen bg-background">
      {/* Header */}
      <header className="border-b border-border bg-card sticky top-0 z-40">
        <div className="container mx-auto px-4 sm:px-6 py-3">
          <div className="flex items-center gap-3">
            <div className="shrink-0">
              <h1 className="text-lg font-semibold text-foreground">
                AI Strategy Copilot
              </h1>
              <p className="text-xs text-muted-foreground hidden sm:block">
                with self-evaluating agents
              </p>
            </div>
            <div className="flex-1 max-w-xl">
              <StockSearch
                onSelect={setSelectedStock}
                selectedStock={selectedStock}
                onClear={handleStockClear}
                disabled={isLoading}
                onSearchChange={setIsSearching}
              />
            </div>
            {/* Flow/Results tabs in header */}
            {(isLoading || showResults) && (
              <TabsList className="shrink-0 grid grid-cols-2 h-9 w-48">
                <TabsTrigger value="flow" className="gap-1.5 text-sm">
                  <RefreshCw className="h-3.5 w-3.5" />
                  Flow
                </TabsTrigger>
                <TabsTrigger value="results" className="gap-1.5 text-sm" disabled={!showResults}>
                  <BarChart3 className="h-3.5 w-3.5" />
                  Results
                </TabsTrigger>
              </TabsList>
            )}
            <Button
              variant="ghost"
              size="icon"
              onClick={() => setIsDark(!isDark)}
              className="h-9 w-9 shrink-0"
            >
              {isDark ? <Sun className="h-4 w-4" /> : <Moon className="h-4 w-4" />}
            </Button>
          </div>
        </div>
      </header>

      <main className="container mx-auto px-4 sm:px-6 pt-4 pb-6 space-y-6 overflow-visible">

        {/* Generate Button */}
        {selectedStock && !showResults && !isLoading && (
          <div className="flex justify-center">
            <Button
              onClick={handleGenerate}
              size="lg"
              className="gap-2 btn-glow"
            >
              <Play className="h-5 w-5" />
              Generate SWOT
            </Button>
          </div>
        )}

        {/* Process Flow - Always visible */}
        <ProcessFlow
          currentStep={currentStep}
          completedSteps={completedSteps}
          mcpStatus={mcpStatus}
          llmProvider={llmProvider}
          cacheHit={cacheHit}
          stockSelected={!!selectedStock}
          isSearching={isSearching}
        />

        {/* Flow Tab - Activity Log during loading */}
        {(isLoading || showResults) && (
          <TabsContent value="flow" className="space-y-6 mt-0">
            {isLoading && <ActivityLog entries={activityLog} />}
          </TabsContent>
        )}

        {/* Results Tab - SWOT cards + metrics */}
        {(isLoading || showResults) && (
          <TabsContent value="results" className="mt-0">
              {analysisResult && (
                <div className="space-y-6 animate-slide-up">
                  {/* Results Header */}
                  <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
                    <div>
                      <h2 className="text-2xl font-semibold text-foreground">
                        {analysisResult.company_name} ({selectedStock?.symbol})
                      </h2>
                      <p className="text-sm text-muted-foreground">
                        {selectedStock?.exchange}
                      </p>
                    </div>
                    <div className="flex flex-wrap items-center gap-4">
                      {/* Metrics */}
                      <div className="flex items-center gap-4">
                        <div className="text-center px-4 py-2 bg-card rounded-lg border">
                          <p className="text-xs text-muted-foreground">Score</p>
                          <p className={`text-xl font-bold ${getScoreColor(analysisResult.score)}`}>
                            {analysisResult.score}/10
                          </p>
                        </div>
                        <div className="text-center px-4 py-2 bg-card rounded-lg border">
                          <p className="text-xs text-muted-foreground">Revisions</p>
                          <p className="text-xl font-bold text-foreground">
                            {analysisResult.revision_count}
                          </p>
                        </div>
                      </div>
                      <Badge variant={getScoreBadge(analysisResult.score).variant} className="gap-1.5">
                        {(() => {
                          const BadgeIcon = getScoreBadge(analysisResult.score).icon
                          return <BadgeIcon className="h-4 w-4" />
                        })()}
                        {getScoreBadge(analysisResult.score).label}
                      </Badge>
                    </div>
                  </div>

                  {/* Export Buttons */}
                  <div className="flex flex-wrap gap-2 print:hidden">
                    <Button variant="outline" size="sm" onClick={copyToClipboard} className="gap-1.5">
                      {copied ? <Check className="h-4 w-4 text-emerald-500" /> : <Copy className="h-4 w-4" />}
                      {copied ? "Copied!" : "Copy"}
                    </Button>
                    <Button variant="outline" size="sm" onClick={downloadAsJson} className="gap-1.5">
                      <Download className="h-4 w-4" />
                      Export JSON
                    </Button>
                    <Button variant="outline" size="sm" onClick={() => window.print()} className="gap-1.5">
                      <Printer className="h-4 w-4" />
                      Print
                    </Button>
                  </div>

                  {/* SWOT Cards */}
                  <div className="grid gap-4 md:grid-cols-2">
                    {/* Strengths Card */}
                    <Card className="border-l-4 border-l-emerald-500">
                      <CardHeader className="pb-3">
                        <CardTitle className="flex items-center gap-2 text-base text-emerald-500">
                          <TrendingUp className="h-5 w-5" />
                          Strengths
                        </CardTitle>
                      </CardHeader>
                      <CardContent>
                        <ul className="space-y-2">
                          {analysisResult.swot_data.strengths.map((item, i) => (
                            <li key={i} className="flex gap-2 text-sm text-foreground">
                              <CheckCircle className="h-4 w-4 text-emerald-500 shrink-0 mt-0.5" />
                              <span>{item}</span>
                            </li>
                          ))}
                        </ul>
                      </CardContent>
                    </Card>

                    {/* Weaknesses Card */}
                    <Card className="border-l-4 border-l-red-500">
                      <CardHeader className="pb-3">
                        <CardTitle className="flex items-center gap-2 text-base text-red-500">
                          <TrendingDown className="h-5 w-5" />
                          Weaknesses
                        </CardTitle>
                      </CardHeader>
                      <CardContent>
                        <ul className="space-y-2">
                          {analysisResult.swot_data.weaknesses.map((item, i) => (
                            <li key={i} className="flex gap-2 text-sm text-foreground">
                              <XCircle className="h-4 w-4 text-red-500 shrink-0 mt-0.5" />
                              <span>{item}</span>
                            </li>
                          ))}
                        </ul>
                      </CardContent>
                    </Card>

                    {/* Opportunities Card */}
                    <Card className="border-l-4 border-l-blue-500">
                      <CardHeader className="pb-3">
                        <CardTitle className="flex items-center gap-2 text-base text-blue-500">
                          <Target className="h-5 w-5" />
                          Opportunities
                        </CardTitle>
                      </CardHeader>
                      <CardContent>
                        <ul className="space-y-2">
                          {analysisResult.swot_data.opportunities.map((item, i) => (
                            <li key={i} className="flex gap-2 text-sm text-foreground">
                              <Zap className="h-4 w-4 text-blue-500 shrink-0 mt-0.5" />
                              <span>{item}</span>
                            </li>
                          ))}
                        </ul>
                      </CardContent>
                    </Card>

                    {/* Threats Card */}
                    <Card className="border-l-4 border-l-yellow-500">
                      <CardHeader className="pb-3">
                        <CardTitle className="flex items-center gap-2 text-base text-yellow-500">
                          <AlertTriangle className="h-5 w-5" />
                          Threats
                        </CardTitle>
                      </CardHeader>
                      <CardContent>
                        <ul className="space-y-2">
                          {analysisResult.swot_data.threats.map((item, i) => (
                            <li key={i} className="flex gap-2 text-sm text-foreground">
                              <AlertCircle className="h-4 w-4 text-yellow-500 shrink-0 mt-0.5" />
                              <span>{item}</span>
                            </li>
                          ))}
                        </ul>
                      </CardContent>
                    </Card>
                  </div>

                  {/* Critic Evaluation */}
                  <Card>
                    <CardHeader>
                      <CardTitle className="text-base flex items-center gap-2">
                        <Target className="h-4 w-4" />
                        Quality Evaluation
                      </CardTitle>
                    </CardHeader>
                    <CardContent>
                      <p className="text-sm text-muted-foreground leading-relaxed">
                        {analysisResult.critique}
                      </p>
                    </CardContent>
                  </Card>
                </div>
              )}
            </TabsContent>
        )}
      </main>

      {/* Footer */}
      <footer className="border-t border-border bg-card mt-auto">
        <div className="container mx-auto px-4 sm:px-6 py-3">
          <div className="flex items-center justify-center gap-4 text-xs text-muted-foreground">
            <span>AI Strategy Copilot</span>
            <span>|</span>
            <span>Multi-agent SWOT analysis</span>
            <span>|</span>
            <span>v2.0</span>
          </div>
        </div>
      </footer>
    </Tabs>
  )
}

const NotFound = () => (
  <div className="min-h-screen bg-background flex flex-col items-center justify-center">
    <div className="text-center space-y-4">
      <h1 className="text-4xl font-bold text-foreground">404</h1>
      <p className="text-xl text-muted-foreground">Page Not Found</p>
      <Button onClick={() => window.location.href = '/'}>Go Home</Button>
    </div>
  </div>
)
